projects:
  theplayerscompany:
    schemaPath: amplify/backend/api/theplayerscompany/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
